### ISSUE TITLE
Does not decrypt my file ? Password not found

### ISSUE THREAD

**Issue by vido89** [glv2/bruteforce-salted-openssl#12]
I have backup from my router which is AES ECB encrypted. I know the key it's `Renjx%2$CjM` but when I try to decrypt it it does not want to, Im not sure why, here is [myfile](https://mega.nz/#!BdBAgIIC!PGZaqaaeKanYqxFtNw5FNsmh_R5UR75Nr0rC8MihJJ0) 
Im using this command 

`$ ./bruteforce-salted-openssl -f ~/Desktop/key ~/Desktop/H201LV2.0_Cur_config.bin -c aes-128-ecb -n 1
`
Here is content of `key` file
```
cat ~/Desktop/key 
Renjx%2$CjM\x00\x00\x00\x00\x00
```

**Comment by glv2** [comment]
The files encrypted by the ```openssl enc ...``` command start with ```Salted__```. Your file is in a different format, therefore *bruteforce-salted-openssl* will not be able to decrypt it.

Maybe this *stackexchange* question could be of some use to you: https://reverseengineering.stackexchange.com/questions/14711/identify-compression-of-this-zte-zxv10-h201l-v2-backup-config-file

**Comment by vido89** [comment]
Yes thats mine stackexchange post, I used -n 1 which will does not compute salt, I was hoping that can decrypt it also with this tool since algorithm is known, I did tried striping header but did not helped. Any way tnx
