### ISSUE TITLE
Is bruteforce-salted-openssl working?

### ISSUE THREAD

**Issue by eribertomota** [glv2/bruteforce-salted-openssl#15]
Hi,

Maybe I am doing something wrong. I was reading #4 and I did a basic test:

`# openssl enc -aes256 -salt -in text.txt -out text.enc`

The key used was 'test'. I can decrypt my text:

```
# openssl enc -d -aes256 -salt -in text.enc -k test
*** WARNING : deprecated key derivation used.
Using -iter or -pbkdf2 would be better.
It is a text.
```

The Salted flag is present:

```
# cat text.enc 
Salted__yi�U�E%�U��*��֏�Xy��;]�
```

However, bruteforce-salted-openssl fails.

```
# bruteforce-salted-openssl -t 2 -f dict -c aes256 text.enc 
Warning: using dictionary mode, ignoring options -b, -e, -l, -m and -s.

Tried passwords: 3
Tried passwords per second: inf
Last tried password: orange

Password not found
```

I attached all used files inside brute.zip. I am using Debian Sid with bruteforce-salted-openssl 1.4.0.

Thanks

Eriberto

[brute.zip](https://github.com/glv2/bruteforce-salted-openssl/files/2479206/brute.zip)

**Comment by glv2** [comment]
What version of openssl are you using?

I am using openssl 1.0.2p and it is unable to decrypt your *text.enc* file:

```
# openssl enc -d -aes256 -salt -in text.enc -k test
bad decrypt
140232888598080:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:evp_enc.c:531:
```

**Comment by eribertomota** [comment]
OpenSSL 1.1.1

**Comment by glv2** [comment]
Apparently, the default hash function used to derive the key has changed. It is MD5 in openssl 1.0.x and SHA256 in openssl 1.1.x.

Specifying explicitly which algorithm to use allows decrypting the file:
```
# bruteforce-salted-openssl -t 2 -d sha256 -f dict text.enc
Warning: using dictionary mode, ignoring options -b, -e, -l, -m and -s.

Tried passwords: 2
Tried passwords per second: inf
Last tried password: orange

Password candidate: test
```

**Comment by eribertomota** [comment]
Hum... Is possible a warning about it in user screen when failing the
command?


Em qua, 17 de out de 2018 às 08:54, glv2 <notifications@github.com>
escreveu:

**Comment by glv2** [comment]
Improved message added in commit 838664ff7651b82814d0c6a828daf32bf566dbeb.

**Comment by eribertomota** [comment]
Thanks!

Em domingo, 21 de outubro de 2018, glv2 <notifications@github.com> escreveu:
