### ISSUE TITLE
Doc improvement proposal - decrypt binary files

### ISSUE THREAD

**Issue by mefistotelis** [glv2/bruteforce-salted-openssl#18]
I'm pretty sure there are people to whom this is news - the tool can be used to decrypt binary files as well. As `.tar.gz` files are quite popular, I'd add to the "Examples" in README:

Try to find the password of a file which was compressed with gzip and then encrypted with des3. Supplying non-text characters via command line (ie. magic values which identify beginning of `gzip` file) may require specific shell - this example is prepared for `bash`. Using 8 threads, trying only passwords up to 9 characters, where characters are digits:

```
./bruteforce-salted-openssl -t 8 -v 5 -c des3 -m 9 -s "0123456789" -M "$(echo -ne "\x1f\x8b")" file.tar.gz.encrypted
```

(I was too lazy for pull request - sorry!)

**Comment by glv2** [comment]
Added in commit 989919fa1996b096714f461a8069766badf66d64, thanks.
