### ISSUE TITLE
Split passphrase crack across multiple PCs

### ISSUE THREAD

**Issue by mungewell** [glv2/bruteforce-salted-openssl#2]
Hi, I see that you have multi-thread support which works nicely. I'd like to be able to split the task across multiple PCs, do you have any suggestions on how the keyspace can be defined for each of the machines?

For example with '-t 2 -s "12345678"' threading appears to test
Thread 1: 1, 2, 3, 4, 11, 12, 13, 14, 15, 16, 17, 18, 21, 22, 23, etc
Thread 2: 5, 6, 7, 8, 51, 52, 53, 54, 55, 56, 57, 58, 61, 62, 63, etc

Do I just hard code a different prefix on different machines, and run multiple times to cover all options?

It would also be nice to be able to restart at particular location in the sequence. Maybe these are the same request...

**Comment by glv2** [comment]
In its current state, the program doesn't contain the code to work on a cluster of computers (like openmpi or equivalent) or to remember the passwords already tried.

But indeed you can run the program several times on several computers and choose different prefixes to test on each one.

**Comment by mungewell** [comment]
Added some logging on my fork. '-L' flag which lets you see what is going on.

$ ./bruteforce-salted-openssl -L 1 -l 2 -m 2 configure.enc_short -N -s "12345678" -t 2

**Comment by mungewell** [comment]
So looking that the '-b' and '-e' options, it is actually quite easy to partition the task between different machines (or even just break it down into smaller, more manageable blocks). These flags automatically  modify the password lengths, so the bulk of the command line remains the same.

So if you have 4 machines available and a character set of '12345678' you might want to do:
$ ./bruteforce-salted-openssl -p '1' ...
$ ./bruteforce-salted-openssl -p '1' ...
$ ./bruteforce-salted-openssl -p '1' ...
$ ./bruteforce-salted-openssl -p '1' ...
