### ISSUE TITLE
Unable to Crack password for pdf file

### ISSUE THREAD

**Issue by i124aq** [glv2/bruteforce-salted-openssl#24]
Hey,

I have a text and a pdf file both encrypted with openssl, I want to crack the passwords for both of them but seems it does not work for pdf whereas for text file it work. Any idea whats wrong or I am missing something? or this tools doesn't support pdf files? Would be thankful if anyone could nudge me in the right direction.

**Comment by glv2** [comment]
Check the ```-M``` option for files that are not mostly ASCII text.
As PDF files start with ```%PDF-```, you could try ```bruteforce-salted-openssl -M "%PDF-" ...```.
