### ISSUE TITLE
password not found while it is present in the dictionary

### ISSUE THREAD

**Issue by mwnoo** [glv2/bruteforce-salted-openssl#4]
Hi,

I can't get your code to work.

Here is an example. I first created an encrypted file with password "test"

```
openssl enc -aes256 -salt -in secret_test.txt -out encrypted.txt -k test
```

Then I tried `bruteforce-salted-openssl` using a wordlist, but the password "test" was not found while it is present in `wordlist.txt`. In the output you can see that the last password tried was "test"

```
bruteforce-salted-openssl -t 2 -f wordlist.txt -c aes256 encrypted.txt

Tried passwords: 6
Tried passwords per second: inf
Last tried password: test
Password not found
```

But when I decrypt the file using openssl with the password "test" the original message is shown

```
openssl enc -d -aes256 -salt -in encrypted.txt -k test
```

Did I miss an option when calling `bruteforce-salted-openssl`?

Thanks,
Mark

**Comment by glv2** [comment]
Maybe your *secret_test.txt* file doesn't contain enough printable ASCII characters, as by default the program considers decrypted data as correct when there is at least 90% of them (see the *Limitations* section of the *README* file).
