### ISSUE TITLE
How to brute force a string?

### ISSUE THREAD

**Issue by ArneAnka** [glv2/bruteforce-salted-openssl#5]
Hi! Lets say I have a string, encrypted with 

`echo "This is a test"|openssl enc -aes-256-cbc -base64 -nosalt`

`w2j7eABqUq2t6HxucMP8hg==`

How to i approach this with a password table?

**Comment by glv2** [comment]
The program currently only works with salted passwords (i.e. encrypted with the ```-salt``` option):
 
    echo "This is a test" | openssl enc -aes-256-cbc -base64 -salt
    U2FsdGVkX1/Q+6o//TDgSajanszT9xshz+MmKHMf9Cs=

If you had the base64 encoding of a string encrypted with a salt, you could do:

    echo U2FsdGVkX1/Q+6o//TDgSajanszT9xshz+MmKHMf9Cs= | base64 -d > data.aes256
    bruteforce-salted-openssl -t 4 -f dictionary-file data.aes256

**Comment by skuran** [comment]
Hello, are you planning to add an -nosalt option to your code. Thank you.
